# These are supported funding model platforms

github: # AustralianDisability
patreon: # adncentral
open_collective: # Replace with a single Open Collective username
ko_fi: # ausdisltd
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # australiandisability
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
paypal: # australiandisabilityltd
